import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '@components/ui'
import Navbar from '../components/common/Navbar/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container>
        <img
          src="https://static.nike.com/a/images/f_auto/dpr_1.0,cs_srgb/w_1589,c_limit/ff82af3e-3e1a-41a3-b1eb-7712136effb1/nike-official-site.jpg"
          className="w-full"
        />
        <div className="my-8 text-center">
          <p className="mb-2">
            Der Nike Pegasus 38 Shield: Dein Arbeitstier mit Flügeln für
            Regentage.
          </p>
          <h4 className="mb-8 text-5xl uppercase font-headline">
            Bleib warm. Bleib trocken. Bleib schnell.
          </h4>
          <a
            href="/"
            className="py-2 font-semibold text-white bg-black rounded-full px-7 hover:bg-gray-800"
          >
            Kaufen
          </a>
        </div>
        <div className="my-20">
          <h2 className="text-2xl">Die richtige Ausrüstung</h2>
          <div className="flex gap-4 my-8 overflow-x-scroll">
            <img
              src="https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/w_525,c_limit/eaad3abc-94cb-442a-8a22-9b006153eb80/react-miler-2-shield-wetterfester-strassenlaufschuh-fur-WnSDPL.png"
              alt=""
            />
            <img
              src="https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/w_525,c_limit/ed177def-b551-43a8-95fa-40353d8fb84f/pegasus-trail-3-gore-tex-wasserfester-trail-laufschuh-fur-herren-FngTl6.png"
              alt=""
            />
            <img
              src="https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/w_591,c_limit/a05f509e-8d66-411e-9ba1-38b64f8bd559/air-zoom-pegasus-38-shield-wetterfester-strassenlaufschuh-fur-herren-BKgmbZ.png"
              alt=""
            />
            <img
              src="https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/w_591,c_limit/aaf5068f-f45c-4492-898b-100b463107ed/air-zoom-pegasus-37-shield-herren-laufschuh-nf5kSS.png"
              alt=""
            />
          </div>
        </div>
      </Container>
    </div>
  )
}

export default Home
